name: run

on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * *"
    - cron: "0 11 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: node setup
        uses: actions/setup-node@v4

      - name: run script
        run: npm start
        env:
          DISCORD_WEBHOOK: ${{secrets.DISCORD_WEBHOOK}}
          PEXELS_API_TOKEN: ${{secrets.PEXELS_API_TOKEN}}
