name: run_main

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * *'
    - cron: '0 11 * * *'

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: python setup
        uses: actions/setup-python@latest
        
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: run script
        env:
          GHA: 1
          DISCORD_WEBHOOK_ID: ${{secrets.DISCORD_WEBHOOK_ID}}
          DISCORD_WEBHOOK_TOKEN: ${{secrets.DISCORD_WEBHOOK_TOKEN}}
          DISCORD_WEBHOOK_BASE: ${{secrets.DISCORD_WEBHOOK_BASE}}
          PEXELS_API_TOKEN: ${{secrets.PEXELS_API_TOKEN}}
          PEXELS_API_BASE: ${{secrets.PEXELS_API_BASE}}
        run: python main.py
