name: run_main

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * *'
    - cron: '0 11 * * *'

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: python setup
        uses: actions/setup-python@v5
        
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: run script
        env:
          DISCORD_WEBHOOK: ${{secrets.DISCORD_WEBHOOK}}
          PEXELS_TOKEN: ${{secrets.PEXELS_TOKEN}}
        run: python main.py
